Assignment of Akshay Naik
javascripters-community/thatjsdude pull request #4
Opened 2017-07-25 12:16 UTC by akshaynaik404

2017-07-25 12:20 UTC, akshaynaik404 commented
Web Application is live at [Newsboard](https://newsboard.tk).

2017-07-25 13:00 UTC, upa8 commented
@akshaynaik404  

Good Job ! ... !!! We will get back to you once we review it.

2017-07-28 07:30 UTC, akshaynaik404 commented
[This](https://github.com/javascripters-community/thatjsdude/pull/4/commits/1034ef0ae858aebaf442fc6248a0583aba2c6da3) Commit will remove the code labs error.

2017-08-15 14:11 UTC, javascripters2015 requested changes
Please update README file with all the required instructions to setup the project for any new person.
Add comments whereever required in code to understand the intention of code implimentation
Avoid inline css and js

Rest of the code quality looks good to us.
Good Job.. keep it up.

2017-08-15 16:23 UTC, akshaynaik404 commented
Thanks for the review.

Although README.md already contains the installation instructions

2017-08-15 16:24 UTC, akshaynaik404 commented
Can you elaborate on inline css, js point?

2017-08-15 16:59 UTC, javascripters2015 reviewed
Please avoid unnecessary ending comma

2017-08-15 16:59 UTC, javascripters2015 commented on public/index.html
> +  <body style="margin: 0">
Avoid inline css

2017-08-15 16:59 UTC, javascripters2015 commented on src/api/index.js
> +  },
Avoid unnecessary comma

2017-08-15 16:59 UTC, javascripters2015 commented on src/components/FabBtn/index.js
> +  },
Avoid unnecessary comma

2017-08-15 17:18 UTC, akshaynaik404 commented on public/index.html
> +  <body style="margin: 0">
Ahh! Yes.  That one. I wrote it inline to avoid creating another styles.css file just for this one rule.

2017-08-15 17:23 UTC, akshaynaik404 commented on src/api/index.js
> +  },
The trailing comma helps in achieving clarity in diffs. [Eslint rule](http://eslint.org/docs/rules/comma-dangle)

2017-08-15 17:40 UTC, akshaynaik404 commented on README.md
> +2. Execute `npm install` or `yarn` on your terminal.
CD into cloned repo directory and then run yarn.

2017-08-16 06:52 UTC, closed without merging